#include "com112_arvoreAVL.h"
#include <stdio.h>

int main(int argc, char *argv[]) {
  NodePtr tree = 0;
  nodeInsert(&tree, 50);
  treePrint2D(tree);
  nodeInsert(&tree, 40);
  treePrint2D(tree);
  nodeInsert(&tree, 60);
  treePrint2D(tree);
  nodeInsert(&tree, 30);
  treePrint2D(tree);
  nodeInsert(&tree, 70);
  treePrint2D(tree);
  nodeInsert(&tree, 20);
  treePrint2D(tree);
  nodeInsert(&tree, 80);
  treePrint2D(tree);
  nodeInsert(&tree, 10);
  treePrint2D(tree);
  nodeInsert(&tree, 90);
  treePrint2D(tree);
  nodeInsert(&tree, 100);
  treePrint2D(tree);
  nodeInsert(&tree, 0);
  treePrint2D(tree);
  nodeInsert(&tree, 35);
  treePrint2D(tree);
  nodeInsert(&tree, 45);
  treePrint2D(tree);
  nodeInsert(&tree, 55);
  treePrint2D(tree);
  nodeInsert(&tree, 65);
  treePrint2D(tree);
  nodeRemove(&tree, 50);
  treePrint2D(tree);
  nodeRemove(&tree, 40);
  treePrint2D(tree);
  nodeRemove(&tree, 60);
  treePrint2D(tree);
  nodeRemove(&tree, 30);
  treePrint2D(tree);
  nodeRemove(&tree, 70);
  treePrint2D(tree);
  nodeRemove(&tree, 20);
  treePrint2D(tree);
  nodeRemove(&tree, 80);
  treePrint2D(tree);
  nodeRemove(&tree, 10);
  treePrint2D(tree);
  nodeRemove(&tree, 90);
  treePrint2D(tree);
  nodeRemove(&tree, 100);
  treePrint2D(tree);
  nodeRemove(&tree, 0);
  treePrint2D(tree);
  nodeRemove(&tree, 35);
  treePrint2D(tree);
  nodeRemove(&tree, 45);
  treePrint2D(tree);
  nodeRemove(&tree, 55);
  treePrint2D(tree);
  nodeRemove(&tree, 65);
  treePrint2D(tree);
  return 0;
}
